### ISSUE TITLE
Not working can not run project

### ISSUE THREAD

**Issue by jwt1029** [AshtonYoon/simsim#1]
![image](https://user-images.githubusercontent.com/14898993/46812214-33fd2880-cdaf-11e8-9f2a-37794b193b20.png)

Not working help
@AshtonYoon

**Comment by kyle-john** [comment]
빌드이후 `bin/Debug` 폴더에 `interception.dll` 이 있는지 확인해보세요

**Comment by AshtonYoon** [comment]
![image](https://user-images.githubusercontent.com/16028154/46848483-123e8880-ce25-11e8-909b-e9e8f1c861b0.png)

**Change configuration**
Any CPU to x64
