### ISSUE TITLE
라이브러리 분석 결과 및 미작동 원인

### ISSUE THREAD

**Issue by jwt1029** [AshtonYoon/simsim#2]
내부 라이브러리를 디버깅 해보니 hardware driver deviceId 가 null을 가리키고 있습니다.
기본적으로 input.Load() 에서 CreateContext를 통해 Context를 생성하고  (<< context가 이 라이브러리에서 의미하는 역할이 무엇인지 파악 필요) Context가 zeroptr이 아닐 경우 Driver 입력을 인식 받는 Callback Thread 를 실행시킵니다. (Input.cs:64~89 참고) CreateContext 시 정상적으로 context가 생성되지 않고 zeroptr 값이 들어와서 device(키보드 드라이버)를 읽어들이는 부분까지 도달하지 못한 것 같습니다.

// 마우스의 경우에는 deviceID가 12로 하드코딩 되어있습니다 (Input.cs:377 참고)

키보드의 경우에는 Callback Thread에서 사용자가 Key Event를 발생시키는 걸 감지하여 그때 키보드 deviceID를 주입시키고 있기 때문에,

1. 직접 키보드 드라이버 deviceID를 알아내어 소스코드에 deviceID를 하드코딩
2. CreateContext() 에서 zeroptr이 반환되는 문제를 해결

을 통해 문제를 해결해야할 것 같습니다.

**Comment by AshtonYoon** [comment]
![image](https://user-images.githubusercontent.com/16028154/46953036-99129000-d0c7-11e8-9ac0-37592c54722f.png)

해결 완료
